import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="mx-auto max-w-7xl">
        <TRPCReactProvider>
          <div className="flex w-full flex-col gap-3">
            <Navbar />
            <div className="max-w-7xl">{children}</div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
